import { CanBeUInteger } from "../utils/ints";
import { CostModelPlutusV3 } from "../v3/CostModelPlutusV3";

// CostModelPlutusV4 extends V3 with PV11 (Dijkstra era) builtins.
// Parameter order follows IntersectMBO/plutus PlutusLedgerApi/V3/ParamName.hs
// (V4 reuses V3 ParamName in the ledger, serialized as CBOR key 3).
export interface CostModelPlutusV4 extends CostModelPlutusV3 {
    "expModInteger-cpu-arguments-coefficient00": CanBeUInteger,
    "expModInteger-cpu-arguments-coefficient11": CanBeUInteger,
    "expModInteger-cpu-arguments-coefficient12": CanBeUInteger,
    "expModInteger-memory-arguments-intercept": CanBeUInteger,
    "expModInteger-memory-arguments-slope": CanBeUInteger,
    "dropList-cpu-arguments-intercept": CanBeUInteger,
    "dropList-cpu-arguments-slope": CanBeUInteger,
    "dropList-memory-arguments": CanBeUInteger,
    "lengthOfArray-cpu-arguments": CanBeUInteger,
    "lengthOfArray-memory-arguments": CanBeUInteger,
    "listToArray-cpu-arguments-intercept": CanBeUInteger,
    "listToArray-cpu-arguments-slope": CanBeUInteger,
    "listToArray-memory-arguments-intercept": CanBeUInteger,
    "listToArray-memory-arguments-slope": CanBeUInteger,
    "indexArray-cpu-arguments": CanBeUInteger,
    "indexArray-memory-arguments": CanBeUInteger,
    "bls12_381_G1_multiScalarMul-cpu-arguments-intercept": CanBeUInteger,
    "bls12_381_G1_multiScalarMul-cpu-arguments-slope": CanBeUInteger,
    "bls12_381_G1_multiScalarMul-memory-arguments": CanBeUInteger,
    "bls12_381_G2_multiScalarMul-cpu-arguments-intercept": CanBeUInteger,
    "bls12_381_G2_multiScalarMul-cpu-arguments-slope": CanBeUInteger,
    "bls12_381_G2_multiScalarMul-memory-arguments": CanBeUInteger,
    "insertCoin-cpu-arguments-intercept": CanBeUInteger,
    "insertCoin-cpu-arguments-slope": CanBeUInteger,
    "insertCoin-memory-arguments-intercept": CanBeUInteger,
    "insertCoin-memory-arguments-slope": CanBeUInteger,
    "lookupCoin-cpu-arguments-intercept": CanBeUInteger,
    "lookupCoin-cpu-arguments-slope": CanBeUInteger,
    "lookupCoin-memory-arguments": CanBeUInteger,
    "unionValue-cpu-arguments-c00": CanBeUInteger,
    "unionValue-cpu-arguments-c10": CanBeUInteger,
    "unionValue-cpu-arguments-c01": CanBeUInteger,
    "unionValue-cpu-arguments-c11": CanBeUInteger,
    "unionValue-memory-arguments-intercept": CanBeUInteger,
    "unionValue-memory-arguments-slope": CanBeUInteger,
    "valueContains-cpu-arguments-constant": CanBeUInteger,
    "valueContains-cpu-arguments-model-arguments-intercept": CanBeUInteger,
    "valueContains-cpu-arguments-model-arguments-slope1": CanBeUInteger,
    "valueContains-cpu-arguments-model-arguments-slope2": CanBeUInteger,
    "valueContains-memory-arguments": CanBeUInteger,
    "valueData-cpu-arguments-intercept": CanBeUInteger,
    "valueData-cpu-arguments-slope": CanBeUInteger,
    "valueData-memory-arguments-intercept": CanBeUInteger,
    "valueData-memory-arguments-slope": CanBeUInteger,
    "unValueData-cpu-arguments-c0": CanBeUInteger,
    "unValueData-cpu-arguments-c1": CanBeUInteger,
    "unValueData-cpu-arguments-c2": CanBeUInteger,
    "unValueData-memory-arguments-intercept": CanBeUInteger,
    "unValueData-memory-arguments-slope": CanBeUInteger,
    "scaleValue-cpu-arguments-intercept": CanBeUInteger,
    "scaleValue-cpu-arguments-slope": CanBeUInteger,
    "scaleValue-memory-arguments-intercept": CanBeUInteger,
    "scaleValue-memory-arguments-slope": CanBeUInteger,
}
